apiVersion: v1
version: 5.2.0
appVersion: 5.2.0
name: service
engine: gotpl
description: Service Helm chart for Kubernetes
home: https://github.com/yoanyombapro1234/FeelGuuds/src/services/reviews_service
maintainers:
    - email: yoanyombapro@gmail.com
      name: yoanyomba
sources:
    - https://github.com/yoanyombapro1234/FeelGuuds/src/services/reviews_service
