name: release-notes

on:
  push:
    branches:
      - 'master'
      - 'release'
      - 'main'

jobs:
  publish-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/release-notes
      - name: Generate release notes
        run: |
          echo 'CHANGELOG' > /tmp/release.txt
          github-release-notes -org stefanprodan -repo podinfo -since-latest-release >> /tmp/release.txt
      - name: Publish release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --release-notes=/tmp/release.txt
          workdir: ./podinfo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
